2023-05-30 17:16:05,937:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-05-30 17:16:05,942:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-05-30 17:16:05,943:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-05-30 17:16:05,944:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2023-05-30 17:16:08,077:WARNING:
'prophet' is a soft dependency and not included in the pycaret installation. Please run: `pip install prophet` to install.
2023-05-30 17:18:49,678:INFO:PyCaret ClassificationExperiment
2023-05-30 17:18:49,680:INFO:Logging name: clf-default-name
2023-05-30 17:18:49,680:INFO:ML Usecase: MLUsecase.CLASSIFICATION
2023-05-30 17:18:49,680:INFO:version 3.0.2
2023-05-30 17:18:49,680:INFO:Initializing setup()
2023-05-30 17:18:49,681:INFO:self.USI: b24f
2023-05-30 17:18:49,682:INFO:self._variable_keys: {'data', 'USI', 'X', 'X_test', 'X_train', 'fold_generator', 'fold_shuffle_param', '_ml_usecase', 'logging_param', 'y_train', '_available_plots', 'target_param', 'n_jobs_param', 'memory', 'seed', 'log_plots_param', 'gpu_param', 'html_param', 'fold_groups_param', 'y_test', 'exp_id', 'idx', 'pipeline', 'exp_name_log', 'y', 'is_multiclass', 'fix_imbalance', 'gpu_n_jobs_param'}
2023-05-30 17:18:49,682:INFO:Checking environment
2023-05-30 17:18:49,682:INFO:python_version: 3.10.11
2023-05-30 17:18:49,682:INFO:python_build: ('tags/v3.10.11:7d4cc5a', 'Apr  5 2023 00:38:17')
2023-05-30 17:18:49,682:INFO:machine: AMD64
2023-05-30 17:18:49,683:INFO:platform: Windows-10-10.0.22621-SP0
2023-05-30 17:18:49,688:INFO:Memory: svmem(total=16947675136, available=3954925568, percent=76.7, used=12992749568, free=3954925568)
2023-05-30 17:18:49,688:INFO:Physical Core: 4
2023-05-30 17:18:49,689:INFO:Logical Core: 8
2023-05-30 17:18:49,689:INFO:Checking libraries
2023-05-30 17:18:49,689:INFO:System:
2023-05-30 17:18:49,690:INFO:    python: 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
2023-05-30 17:18:49,691:INFO:executable: c:\Users\Jef\AppData\Local\Programs\Python\Python310\python.exe
2023-05-30 17:18:49,691:INFO:   machine: Windows-10-10.0.22621-SP0
2023-05-30 17:18:49,691:INFO:PyCaret required dependencies:
2023-05-30 17:18:49,692:INFO:                 pip: 23.1.2
2023-05-30 17:18:49,692:INFO:          setuptools: 65.5.0
2023-05-30 17:18:49,693:INFO:             pycaret: 3.0.2
2023-05-30 17:18:49,693:INFO:             IPython: 7.34.0
2023-05-30 17:18:49,694:INFO:          ipywidgets: 7.7.5
2023-05-30 17:18:49,694:INFO:                tqdm: 4.65.0
2023-05-30 17:18:49,694:INFO:               numpy: 1.23.0
2023-05-30 17:18:49,695:INFO:              pandas: 1.5.3
2023-05-30 17:18:49,695:INFO:              jinja2: 3.1.2
2023-05-30 17:18:49,695:INFO:               scipy: 1.10.1
2023-05-30 17:18:49,696:INFO:              joblib: 1.2.0
2023-05-30 17:18:49,696:INFO:             sklearn: 1.2.2
2023-05-30 17:18:49,696:INFO:                pyod: 1.0.9
2023-05-30 17:18:49,696:INFO:            imblearn: 0.10.1
2023-05-30 17:18:49,696:INFO:   category_encoders: 2.6.1
2023-05-30 17:18:49,697:INFO:            lightgbm: 3.3.5
2023-05-30 17:18:49,697:INFO:               numba: 0.57.0
2023-05-30 17:18:49,697:INFO:            requests: 2.31.0
2023-05-30 17:18:49,697:INFO:          matplotlib: 3.7.1
2023-05-30 17:18:49,699:INFO:          scikitplot: 0.3.7
2023-05-30 17:18:49,699:INFO:         yellowbrick: 1.5
2023-05-30 17:18:49,699:INFO:              plotly: 5.14.1
2023-05-30 17:18:49,699:INFO:             kaleido: 0.2.1
2023-05-30 17:18:49,699:INFO:         statsmodels: 0.14.0
2023-05-30 17:18:49,699:INFO:              sktime: 0.17.0
2023-05-30 17:18:49,699:INFO:               tbats: 1.1.3
2023-05-30 17:18:49,700:INFO:            pmdarima: 2.0.3
2023-05-30 17:18:49,700:INFO:              psutil: 5.9.5
2023-05-30 17:18:49,700:INFO:PyCaret optional dependencies:
2023-05-30 17:18:52,450:INFO:                shap: 0.41.0
2023-05-30 17:18:52,450:INFO:           interpret: 0.4.1
2023-05-30 17:18:52,451:INFO:                umap: 0.5.3
2023-05-30 17:18:52,451:INFO:    pandas_profiling: 4.2.0
2023-05-30 17:18:52,454:INFO:  explainerdashboard: 0.4.2.2
2023-05-30 17:18:52,454:INFO:             autoviz: 0.1.604
2023-05-30 17:18:52,455:INFO:           fairlearn: 0.7.0
2023-05-30 17:18:52,456:INFO:             xgboost: 1.7.5
2023-05-30 17:18:52,457:INFO:            catboost: 1.2
2023-05-30 17:18:52,458:INFO:              kmodes: 0.12.2
2023-05-30 17:18:52,458:INFO:             mlxtend: 0.22.0
2023-05-30 17:18:52,458:INFO:       statsforecast: 1.5.0
2023-05-30 17:18:52,458:INFO:        tune_sklearn: 0.4.5
2023-05-30 17:18:52,459:INFO:                 ray: 2.4.0
2023-05-30 17:18:52,459:INFO:            hyperopt: 0.2.7
2023-05-30 17:18:52,459:INFO:              optuna: 3.1.1
2023-05-30 17:18:52,461:INFO:               skopt: 0.9.0
2023-05-30 17:18:52,462:INFO:              mlflow: 1.30.1
2023-05-30 17:18:52,462:INFO:              gradio: 3.32.0
2023-05-30 17:18:52,462:INFO:             fastapi: 0.95.2
2023-05-30 17:18:52,463:INFO:             uvicorn: 0.22.0
2023-05-30 17:18:52,463:INFO:              m2cgen: 0.10.0
2023-05-30 17:18:52,463:INFO:           evidently: 0.2.8
2023-05-30 17:18:52,463:INFO:               fugue: 0.8.4
2023-05-30 17:18:52,464:INFO:           streamlit: 1.22.0
2023-05-30 17:18:52,464:INFO:             prophet: Not installed
2023-05-30 17:18:52,464:INFO:None
2023-05-30 17:18:52,464:INFO:Set up data.
2023-05-30 17:24:45,880:INFO:PyCaret ClassificationExperiment
2023-05-30 17:24:45,900:INFO:Logging name: clf-default-name
2023-05-30 17:24:45,901:INFO:ML Usecase: MLUsecase.CLASSIFICATION
2023-05-30 17:24:45,901:INFO:version 3.0.2
2023-05-30 17:24:45,902:INFO:Initializing setup()
2023-05-30 17:24:45,902:INFO:self.USI: 4cc7
2023-05-30 17:24:45,902:INFO:self._variable_keys: {'data', 'USI', 'X', 'X_test', 'X_train', 'fold_generator', 'fold_shuffle_param', '_ml_usecase', 'logging_param', 'y_train', '_available_plots', 'target_param', 'n_jobs_param', 'memory', 'seed', 'log_plots_param', 'gpu_param', 'html_param', 'fold_groups_param', 'y_test', 'exp_id', 'idx', 'pipeline', 'exp_name_log', 'y', 'is_multiclass', 'fix_imbalance', 'gpu_n_jobs_param'}
2023-05-30 17:24:45,902:INFO:Checking environment
2023-05-30 17:24:45,903:INFO:python_version: 3.10.11
2023-05-30 17:24:45,904:INFO:python_build: ('tags/v3.10.11:7d4cc5a', 'Apr  5 2023 00:38:17')
2023-05-30 17:24:45,904:INFO:machine: AMD64
2023-05-30 17:24:45,904:INFO:platform: Windows-10-10.0.22621-SP0
2023-05-30 17:24:45,908:INFO:Memory: svmem(total=16947675136, available=3946909696, percent=76.7, used=13000765440, free=3946909696)
2023-05-30 17:24:45,908:INFO:Physical Core: 4
2023-05-30 17:24:45,908:INFO:Logical Core: 8
2023-05-30 17:24:45,908:INFO:Checking libraries
2023-05-30 17:24:45,910:INFO:System:
2023-05-30 17:24:45,910:INFO:    python: 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
2023-05-30 17:24:45,910:INFO:executable: c:\Users\Jef\AppData\Local\Programs\Python\Python310\python.exe
2023-05-30 17:24:45,910:INFO:   machine: Windows-10-10.0.22621-SP0
2023-05-30 17:24:45,912:INFO:PyCaret required dependencies:
2023-05-30 17:24:45,914:INFO:                 pip: 23.1.2
2023-05-30 17:24:45,915:INFO:          setuptools: 65.5.0
2023-05-30 17:24:45,915:INFO:             pycaret: 3.0.2
2023-05-30 17:24:45,916:INFO:             IPython: 7.34.0
2023-05-30 17:24:45,916:INFO:          ipywidgets: 7.7.5
2023-05-30 17:24:45,917:INFO:                tqdm: 4.65.0
2023-05-30 17:24:45,917:INFO:               numpy: 1.23.0
2023-05-30 17:24:45,918:INFO:              pandas: 1.5.3
2023-05-30 17:24:45,918:INFO:              jinja2: 3.1.2
2023-05-30 17:24:45,919:INFO:               scipy: 1.10.1
2023-05-30 17:24:45,919:INFO:              joblib: 1.2.0
2023-05-30 17:24:45,919:INFO:             sklearn: 1.2.2
2023-05-30 17:24:45,920:INFO:                pyod: 1.0.9
2023-05-30 17:24:45,920:INFO:            imblearn: 0.10.1
2023-05-30 17:24:45,920:INFO:   category_encoders: 2.6.1
2023-05-30 17:24:45,921:INFO:            lightgbm: 3.3.5
2023-05-30 17:24:45,921:INFO:               numba: 0.57.0
2023-05-30 17:24:45,922:INFO:            requests: 2.31.0
2023-05-30 17:24:45,922:INFO:          matplotlib: 3.7.1
2023-05-30 17:24:45,922:INFO:          scikitplot: 0.3.7
2023-05-30 17:24:45,923:INFO:         yellowbrick: 1.5
2023-05-30 17:24:45,923:INFO:              plotly: 5.14.1
2023-05-30 17:24:45,923:INFO:             kaleido: 0.2.1
2023-05-30 17:24:45,923:INFO:         statsmodels: 0.14.0
2023-05-30 17:24:45,924:INFO:              sktime: 0.17.0
2023-05-30 17:24:45,924:INFO:               tbats: 1.1.3
2023-05-30 17:24:45,924:INFO:            pmdarima: 2.0.3
2023-05-30 17:24:45,924:INFO:              psutil: 5.9.5
2023-05-30 17:24:45,925:INFO:PyCaret optional dependencies:
2023-05-30 17:24:45,925:INFO:                shap: 0.41.0
2023-05-30 17:24:45,925:INFO:           interpret: 0.4.1
2023-05-30 17:24:45,926:INFO:                umap: 0.5.3
2023-05-30 17:24:45,926:INFO:    pandas_profiling: 4.2.0
2023-05-30 17:24:45,926:INFO:  explainerdashboard: 0.4.2.2
2023-05-30 17:24:45,926:INFO:             autoviz: 0.1.604
2023-05-30 17:24:45,927:INFO:           fairlearn: 0.7.0
2023-05-30 17:24:45,927:INFO:             xgboost: 1.7.5
2023-05-30 17:24:45,928:INFO:            catboost: 1.2
2023-05-30 17:24:45,929:INFO:              kmodes: 0.12.2
2023-05-30 17:24:45,930:INFO:             mlxtend: 0.22.0
2023-05-30 17:24:45,932:INFO:       statsforecast: 1.5.0
2023-05-30 17:24:45,932:INFO:        tune_sklearn: 0.4.5
2023-05-30 17:24:45,933:INFO:                 ray: 2.4.0
2023-05-30 17:24:45,933:INFO:            hyperopt: 0.2.7
2023-05-30 17:24:45,934:INFO:              optuna: 3.1.1
2023-05-30 17:24:45,934:INFO:               skopt: 0.9.0
2023-05-30 17:24:45,935:INFO:              mlflow: 1.30.1
2023-05-30 17:24:45,935:INFO:              gradio: 3.32.0
2023-05-30 17:24:45,936:INFO:             fastapi: 0.95.2
2023-05-30 17:24:45,937:INFO:             uvicorn: 0.22.0
2023-05-30 17:24:45,937:INFO:              m2cgen: 0.10.0
2023-05-30 17:24:45,938:INFO:           evidently: 0.2.8
2023-05-30 17:24:45,938:INFO:               fugue: 0.8.4
2023-05-30 17:24:45,938:INFO:           streamlit: 1.22.0
2023-05-30 17:24:45,939:INFO:             prophet: Not installed
2023-05-30 17:24:45,939:INFO:None
2023-05-30 17:24:45,939:INFO:Set up data.
2023-05-30 17:24:45,948:INFO:Set up train/test split.
2023-05-30 17:24:45,954:INFO:Set up index.
2023-05-30 17:24:45,954:INFO:Set up folding strategy.
2023-05-30 17:24:45,955:INFO:Assigning column types.
2023-05-30 17:24:45,959:INFO:Engine successfully changes for model 'lr' to 'sklearn'.
2023-05-30 17:24:46,008:INFO:Engine for model 'knn' has not been set explicitly, hence returning None.
2023-05-30 17:24:46,016:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2023-05-30 17:24:46,058:INFO:Soft dependency imported: xgboost: 1.7.5
2023-05-30 17:24:47,000:INFO:Soft dependency imported: catboost: 1.2
2023-05-30 17:24:47,494:INFO:Engine for model 'knn' has not been set explicitly, hence returning None.
2023-05-30 17:24:47,496:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2023-05-30 17:24:47,526:INFO:Soft dependency imported: xgboost: 1.7.5
2023-05-30 17:24:47,530:INFO:Soft dependency imported: catboost: 1.2
2023-05-30 17:24:47,532:INFO:Engine successfully changes for model 'knn' to 'sklearn'.
2023-05-30 17:24:47,578:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2023-05-30 17:24:47,606:INFO:Soft dependency imported: xgboost: 1.7.5
2023-05-30 17:24:47,610:INFO:Soft dependency imported: catboost: 1.2
2023-05-30 17:24:47,659:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2023-05-30 17:24:47,689:INFO:Soft dependency imported: xgboost: 1.7.5
2023-05-30 17:24:47,692:INFO:Soft dependency imported: catboost: 1.2
2023-05-30 17:24:47,693:INFO:Engine successfully changes for model 'rbfsvm' to 'sklearn'.
2023-05-30 17:24:47,770:INFO:Soft dependency imported: xgboost: 1.7.5
2023-05-30 17:24:47,773:INFO:Soft dependency imported: catboost: 1.2
2023-05-30 17:24:47,850:INFO:Soft dependency imported: xgboost: 1.7.5
2023-05-30 17:24:47,853:INFO:Soft dependency imported: catboost: 1.2
2023-05-30 17:24:47,855:INFO:Preparing preprocessing pipeline...
2023-05-30 17:24:47,856:INFO:Set up simple imputation.
2023-05-30 17:24:47,861:INFO:Set up encoding of ordinal features.
2023-05-30 17:24:47,866:INFO:Set up encoding of categorical features.
2023-05-30 17:24:47,985:INFO:Finished creating preprocessing pipeline.
2023-05-30 17:24:48,052:INFO:Pipeline: Pipeline(memory=FastMemory(location=C:\Users\Jef\AppData\Local\Temp\joblib),
         steps=[('numerical_imputer',
                 TransformerWrapper(exclude=None,
                                    include=['age', 'trestbps', 'chol',
                                             'oldpeak', 'slope', 'ca', 'thal'],
                                    transformer=SimpleImputer(add_indicator=False,
                                                              copy=True,
                                                              fill_value=None,
                                                              keep_empty_features=False,
                                                              missing_values=nan,
                                                              strategy='mean',
                                                              verbose='deprecat...
                                                              handle_missing='return_nan',
                                                              handle_unknown='value',
                                                              return_df=True,
                                                              use_cat_names=True,
                                                              verbose=0))),
                ('rest_encoding',
                 TransformerWrapper(exclude=None, include=['thalach'],
                                    transformer=TargetEncoder(cols=[],
                                                              drop_invariant=False,
                                                              handle_missing='return_nan',
                                                              handle_unknown='value',
                                                              hierarchy=None,
                                                              min_samples_leaf=20,
                                                              return_df=True,
                                                              smoothing=10,
                                                              verbose=0)))],
         verbose=False)
2023-05-30 17:24:48,052:INFO:Creating final display dataframe.
2023-05-30 17:24:48,333:INFO:Setup _display_container:                     Description             Value
0                    Session id              5668
1                        Target            target
2                   Target type            Binary
3           Original data shape         (303, 14)
4        Transformed data shape         (303, 19)
5   Transformed train set shape         (212, 19)
6    Transformed test set shape          (91, 19)
7              Ordinal features                 3
8              Numeric features                 7
9          Categorical features                 6
10                   Preprocess              True
11              Imputation type            simple
12           Numeric imputation              mean
13       Categorical imputation              mode
14     Maximum one-hot encoding                25
15              Encoding method              None
16               Fold Generator   StratifiedKFold
17                  Fold Number                10
18                     CPU Jobs                -1
19                      Use GPU             False
20               Log Experiment             False
21              Experiment Name  clf-default-name
22                          USI              4cc7
2023-05-30 17:24:48,432:INFO:Soft dependency imported: xgboost: 1.7.5
2023-05-30 17:24:48,434:INFO:Soft dependency imported: catboost: 1.2
2023-05-30 17:24:48,510:INFO:Soft dependency imported: xgboost: 1.7.5
2023-05-30 17:24:48,515:INFO:Soft dependency imported: catboost: 1.2
2023-05-30 17:24:48,516:INFO:setup() successfully completed in 2.91s...............
2023-05-30 17:25:27,764:INFO:Initializing compare_models()
2023-05-30 17:25:27,765:INFO:compare_models(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000023F2193E890>, include=None, fold=None, round=4, cross_validation=True, sort=Accuracy, n_select=1, budget_time=None, turbo=True, errors=ignore, fit_kwargs=None, groups=None, experiment_custom_tags=None, probability_threshold=None, verbose=True, parallel=None, caller_params={'self': <pycaret.classification.oop.ClassificationExperiment object at 0x0000023F2193E890>, 'include': None, 'exclude': None, 'fold': None, 'round': 4, 'cross_validation': True, 'sort': 'Accuracy', 'n_select': 1, 'budget_time': None, 'turbo': True, 'errors': 'ignore', 'fit_kwargs': None, 'groups': None, 'experiment_custom_tags': None, 'probability_threshold': None, 'engine': None, 'verbose': True, 'parallel': None, '__class__': <class 'pycaret.classification.oop.ClassificationExperiment'>}, exclude=None)
2023-05-30 17:25:27,765:INFO:Checking exceptions
2023-05-30 17:25:27,772:INFO:Preparing display monitor
2023-05-30 17:25:27,826:INFO:Initializing Logistic Regression
2023-05-30 17:25:27,827:INFO:Total runtime is 1.6677379608154298e-05 minutes
2023-05-30 17:25:27,835:INFO:SubProcess create_model() called ==================================
2023-05-30 17:25:27,836:INFO:Initializing create_model()
2023-05-30 17:25:27,836:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000023F2193E890>, estimator=lr, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000023F1F325E70>, model_only=True, return_train_score=False, kwargs={})
2023-05-30 17:25:27,837:INFO:Checking exceptions
2023-05-30 17:25:27,837:INFO:Importing libraries
2023-05-30 17:25:27,838:INFO:Copying training dataset
2023-05-30 17:25:27,848:INFO:Defining folds
2023-05-30 17:25:27,849:INFO:Declaring metric variables
2023-05-30 17:25:27,857:INFO:Importing untrained model
2023-05-30 17:25:27,864:INFO:Logistic Regression Imported successfully
2023-05-30 17:25:27,883:INFO:Starting cross validation
2023-05-30 17:25:27,887:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-05-30 17:25:36,188:WARNING:c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

2023-05-30 17:25:36,206:WARNING:c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

2023-05-30 17:25:37,734:WARNING:c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

2023-05-30 17:25:39,444:INFO:Calculating mean and std
2023-05-30 17:25:39,446:INFO:Creating metrics dataframe
2023-05-30 17:25:39,858:INFO:Uploading results into container
2023-05-30 17:25:39,860:INFO:Uploading model into container now
2023-05-30 17:25:39,861:INFO:_master_model_container: 1
2023-05-30 17:25:39,861:INFO:_display_container: 2
2023-05-30 17:25:39,862:INFO:LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=5668, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)
2023-05-30 17:25:39,863:INFO:create_model() successfully completed......................................
2023-05-30 17:25:39,998:INFO:SubProcess create_model() end ==================================
2023-05-30 17:25:39,998:INFO:Creating metrics dataframe
2023-05-30 17:25:40,015:INFO:Initializing K Neighbors Classifier
2023-05-30 17:25:40,016:INFO:Total runtime is 0.2031604806582133 minutes
2023-05-30 17:25:40,020:INFO:SubProcess create_model() called ==================================
2023-05-30 17:25:40,022:INFO:Initializing create_model()
2023-05-30 17:25:40,022:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000023F2193E890>, estimator=knn, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000023F1F325E70>, model_only=True, return_train_score=False, kwargs={})
2023-05-30 17:25:40,023:INFO:Checking exceptions
2023-05-30 17:25:40,023:INFO:Importing libraries
2023-05-30 17:25:40,023:INFO:Copying training dataset
2023-05-30 17:25:40,030:INFO:Defining folds
2023-05-30 17:25:40,030:INFO:Declaring metric variables
2023-05-30 17:25:40,036:INFO:Importing untrained model
2023-05-30 17:25:40,040:INFO:K Neighbors Classifier Imported successfully
2023-05-30 17:25:40,050:INFO:Starting cross validation
2023-05-30 17:25:40,053:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-05-30 17:25:44,619:INFO:Calculating mean and std
2023-05-30 17:25:44,621:INFO:Creating metrics dataframe
2023-05-30 17:25:45,214:INFO:Uploading results into container
2023-05-30 17:25:45,216:INFO:Uploading model into container now
2023-05-30 17:25:45,216:INFO:_master_model_container: 2
2023-05-30 17:25:45,218:INFO:_display_container: 2
2023-05-30 17:25:45,218:INFO:KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=-1, n_neighbors=5, p=2,
                     weights='uniform')
2023-05-30 17:25:45,219:INFO:create_model() successfully completed......................................
2023-05-30 17:25:45,391:INFO:SubProcess create_model() end ==================================
2023-05-30 17:25:45,392:INFO:Creating metrics dataframe
2023-05-30 17:25:45,420:INFO:Initializing Naive Bayes
2023-05-30 17:25:45,420:INFO:Total runtime is 0.29323224226633704 minutes
2023-05-30 17:25:45,430:INFO:SubProcess create_model() called ==================================
2023-05-30 17:25:45,431:INFO:Initializing create_model()
2023-05-30 17:25:45,432:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000023F2193E890>, estimator=nb, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000023F1F325E70>, model_only=True, return_train_score=False, kwargs={})
2023-05-30 17:25:45,432:INFO:Checking exceptions
2023-05-30 17:25:45,433:INFO:Importing libraries
2023-05-30 17:25:45,434:INFO:Copying training dataset
2023-05-30 17:25:45,446:INFO:Defining folds
2023-05-30 17:25:45,447:INFO:Declaring metric variables
2023-05-30 17:25:45,456:INFO:Importing untrained model
2023-05-30 17:25:45,465:INFO:Naive Bayes Imported successfully
2023-05-30 17:25:45,480:INFO:Starting cross validation
2023-05-30 17:25:45,483:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-05-30 17:25:50,314:INFO:Calculating mean and std
2023-05-30 17:25:50,316:INFO:Creating metrics dataframe
2023-05-30 17:25:50,777:INFO:Uploading results into container
2023-05-30 17:25:50,778:INFO:Uploading model into container now
2023-05-30 17:25:50,780:INFO:_master_model_container: 3
2023-05-30 17:25:50,780:INFO:_display_container: 2
2023-05-30 17:25:50,781:INFO:GaussianNB(priors=None, var_smoothing=1e-09)
2023-05-30 17:25:50,781:INFO:create_model() successfully completed......................................
2023-05-30 17:25:50,933:INFO:SubProcess create_model() end ==================================
2023-05-30 17:25:50,934:INFO:Creating metrics dataframe
2023-05-30 17:25:50,954:INFO:Initializing Decision Tree Classifier
2023-05-30 17:25:50,955:INFO:Total runtime is 0.38547816673914587 minutes
2023-05-30 17:25:50,960:INFO:SubProcess create_model() called ==================================
2023-05-30 17:25:50,962:INFO:Initializing create_model()
2023-05-30 17:25:50,962:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000023F2193E890>, estimator=dt, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000023F1F325E70>, model_only=True, return_train_score=False, kwargs={})
2023-05-30 17:25:50,963:INFO:Checking exceptions
2023-05-30 17:25:50,963:INFO:Importing libraries
2023-05-30 17:25:50,963:INFO:Copying training dataset
2023-05-30 17:25:50,968:INFO:Defining folds
2023-05-30 17:25:50,970:INFO:Declaring metric variables
2023-05-30 17:25:50,975:INFO:Importing untrained model
2023-05-30 17:25:50,982:INFO:Decision Tree Classifier Imported successfully
2023-05-30 17:25:50,990:INFO:Starting cross validation
2023-05-30 17:25:50,993:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-05-30 17:25:55,203:INFO:Calculating mean and std
2023-05-30 17:25:55,206:INFO:Creating metrics dataframe
2023-05-30 17:25:55,648:INFO:Uploading results into container
2023-05-30 17:25:55,650:INFO:Uploading model into container now
2023-05-30 17:25:55,651:INFO:_master_model_container: 4
2023-05-30 17:25:55,652:INFO:_display_container: 2
2023-05-30 17:25:55,652:INFO:DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       random_state=5668, splitter='best')
2023-05-30 17:25:55,654:INFO:create_model() successfully completed......................................
2023-05-30 17:25:55,793:INFO:SubProcess create_model() end ==================================
2023-05-30 17:25:55,794:INFO:Creating metrics dataframe
2023-05-30 17:25:55,815:INFO:Initializing SVM - Linear Kernel
2023-05-30 17:25:55,815:INFO:Total runtime is 0.4664743026097615 minutes
2023-05-30 17:25:55,821:INFO:SubProcess create_model() called ==================================
2023-05-30 17:25:55,822:INFO:Initializing create_model()
2023-05-30 17:25:55,822:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000023F2193E890>, estimator=svm, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000023F1F325E70>, model_only=True, return_train_score=False, kwargs={})
2023-05-30 17:25:55,823:INFO:Checking exceptions
2023-05-30 17:25:55,823:INFO:Importing libraries
2023-05-30 17:25:55,823:INFO:Copying training dataset
2023-05-30 17:25:55,830:INFO:Defining folds
2023-05-30 17:25:55,831:INFO:Declaring metric variables
2023-05-30 17:25:55,837:INFO:Importing untrained model
2023-05-30 17:25:55,842:INFO:SVM - Linear Kernel Imported successfully
2023-05-30 17:25:55,850:INFO:Starting cross validation
2023-05-30 17:25:55,852:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-05-30 17:25:56,673:WARNING:c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
  File "c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-05-30 17:25:56,675:WARNING:c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
  File "c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-05-30 17:25:56,684:WARNING:c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
  File "c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-05-30 17:25:57,803:WARNING:c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
  File "c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-05-30 17:25:57,836:WARNING:c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
  File "c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\_available_if.py", line 32, in __get__
    if not self.check(obj):
  File "c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py", line 1235, in _check_proba
    raise AttributeError(
AttributeError: probability estimates are not available for loss='hinge'

  warnings.warn(

2023-05-30 17:25:59,756:INFO:Calculating mean and std
2023-05-30 17:25:59,758:INFO:Creating metrics dataframe
2023-05-30 17:26:00,248:INFO:Uploading results into container
2023-05-30 17:26:00,250:INFO:Uploading model into container now
2023-05-30 17:26:00,251:INFO:_master_model_container: 5
2023-05-30 17:26:00,251:INFO:_display_container: 2
2023-05-30 17:26:00,252:INFO:SGDClassifier(alpha=0.0001, average=False, class_weight=None,
              early_stopping=False, epsilon=0.1, eta0=0.001, fit_intercept=True,
              l1_ratio=0.15, learning_rate='optimal', loss='hinge',
              max_iter=1000, n_iter_no_change=5, n_jobs=-1, penalty='l2',
              power_t=0.5, random_state=5668, shuffle=True, tol=0.001,
              validation_fraction=0.1, verbose=0, warm_start=False)
2023-05-30 17:26:00,253:INFO:create_model() successfully completed......................................
2023-05-30 17:26:00,390:INFO:SubProcess create_model() end ==================================
2023-05-30 17:26:00,391:INFO:Creating metrics dataframe
2023-05-30 17:26:00,412:INFO:Initializing Ridge Classifier
2023-05-30 17:26:00,412:INFO:Total runtime is 0.5430957198143005 minutes
2023-05-30 17:26:00,418:INFO:SubProcess create_model() called ==================================
2023-05-30 17:26:00,420:INFO:Initializing create_model()
2023-05-30 17:26:00,420:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000023F2193E890>, estimator=ridge, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000023F1F325E70>, model_only=True, return_train_score=False, kwargs={})
2023-05-30 17:26:00,421:INFO:Checking exceptions
2023-05-30 17:26:00,421:INFO:Importing libraries
2023-05-30 17:26:00,421:INFO:Copying training dataset
2023-05-30 17:26:00,427:INFO:Defining folds
2023-05-30 17:26:00,428:INFO:Declaring metric variables
2023-05-30 17:26:00,434:INFO:Importing untrained model
2023-05-30 17:26:00,438:INFO:Ridge Classifier Imported successfully
2023-05-30 17:26:00,445:INFO:Starting cross validation
2023-05-30 17:26:00,447:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-05-30 17:26:01,123:WARNING:c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-05-30 17:26:01,133:WARNING:c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-05-30 17:26:01,138:WARNING:c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-05-30 17:26:01,165:WARNING:c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-05-30 17:26:01,202:WARNING:c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-05-30 17:26:01,213:WARNING:c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-05-30 17:26:01,247:WARNING:c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-05-30 17:26:02,441:WARNING:c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-05-30 17:26:02,454:WARNING:c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\pycaret\internal\metrics.py:138: FitFailedWarning: Metric 'make_scorer(roc_auc_score, needs_proba=True, error_score=0.0, average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_scorer.py", line 76, in _cached_call
    return cache[method]
KeyError: 'predict_proba'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\pycaret\internal\metrics.py", line 130, in _score
    return super()._score(
  File "c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_scorer.py", line 316, in _score
    y_pred = method_caller(clf, "predict_proba", X)
  File "c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_scorer.py", line 78, in _cached_call
    result = getattr(estimator, method)(*args, **kwargs)
  File "c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\pycaret\internal\pipeline.py", line 121, in __getattr__
    return getattr(self._final_estimator, name)
AttributeError: 'RidgeClassifier' object has no attribute 'predict_proba'

  warnings.warn(

2023-05-30 17:26:04,441:INFO:Calculating mean and std
2023-05-30 17:26:04,443:INFO:Creating metrics dataframe
2023-05-30 17:26:04,922:INFO:Uploading results into container
2023-05-30 17:26:04,924:INFO:Uploading model into container now
2023-05-30 17:26:04,925:INFO:_master_model_container: 6
2023-05-30 17:26:04,926:INFO:_display_container: 2
2023-05-30 17:26:04,927:INFO:RidgeClassifier(alpha=1.0, class_weight=None, copy_X=True, fit_intercept=True,
                max_iter=None, positive=False, random_state=5668, solver='auto',
                tol=0.0001)
2023-05-30 17:26:04,927:INFO:create_model() successfully completed......................................
2023-05-30 17:26:05,061:INFO:SubProcess create_model() end ==================================
2023-05-30 17:26:05,062:INFO:Creating metrics dataframe
2023-05-30 17:26:05,081:INFO:Initializing Random Forest Classifier
2023-05-30 17:26:05,082:INFO:Total runtime is 0.6209324359893799 minutes
2023-05-30 17:26:05,087:INFO:SubProcess create_model() called ==================================
2023-05-30 17:26:05,088:INFO:Initializing create_model()
2023-05-30 17:26:05,088:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000023F2193E890>, estimator=rf, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000023F1F325E70>, model_only=True, return_train_score=False, kwargs={})
2023-05-30 17:26:05,090:INFO:Checking exceptions
2023-05-30 17:26:05,090:INFO:Importing libraries
2023-05-30 17:26:05,090:INFO:Copying training dataset
2023-05-30 17:26:05,097:INFO:Defining folds
2023-05-30 17:26:05,098:INFO:Declaring metric variables
2023-05-30 17:26:05,102:INFO:Importing untrained model
2023-05-30 17:26:05,107:INFO:Random Forest Classifier Imported successfully
2023-05-30 17:26:05,114:INFO:Starting cross validation
2023-05-30 17:26:05,117:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-05-30 17:26:11,050:INFO:Calculating mean and std
2023-05-30 17:26:11,052:INFO:Creating metrics dataframe
2023-05-30 17:26:11,611:INFO:Uploading results into container
2023-05-30 17:26:11,613:INFO:Uploading model into container now
2023-05-30 17:26:11,616:INFO:_master_model_container: 7
2023-05-30 17:26:11,617:INFO:_display_container: 2
2023-05-30 17:26:11,618:INFO:RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='sqrt',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       n_estimators=100, n_jobs=-1, oob_score=False,
                       random_state=5668, verbose=0, warm_start=False)
2023-05-30 17:26:11,619:INFO:create_model() successfully completed......................................
2023-05-30 17:26:11,772:INFO:SubProcess create_model() end ==================================
2023-05-30 17:26:11,772:INFO:Creating metrics dataframe
2023-05-30 17:26:11,793:INFO:Initializing Quadratic Discriminant Analysis
2023-05-30 17:26:11,795:INFO:Total runtime is 0.7328097025553385 minutes
2023-05-30 17:26:11,805:INFO:SubProcess create_model() called ==================================
2023-05-30 17:26:11,806:INFO:Initializing create_model()
2023-05-30 17:26:11,806:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000023F2193E890>, estimator=qda, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000023F1F325E70>, model_only=True, return_train_score=False, kwargs={})
2023-05-30 17:26:11,806:INFO:Checking exceptions
2023-05-30 17:26:11,807:INFO:Importing libraries
2023-05-30 17:26:11,807:INFO:Copying training dataset
2023-05-30 17:26:11,815:INFO:Defining folds
2023-05-30 17:26:11,816:INFO:Declaring metric variables
2023-05-30 17:26:11,821:INFO:Importing untrained model
2023-05-30 17:26:11,825:INFO:Quadratic Discriminant Analysis Imported successfully
2023-05-30 17:26:11,835:INFO:Starting cross validation
2023-05-30 17:26:11,838:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-05-30 17:26:12,242:WARNING:c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\discriminant_analysis.py:926: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2023-05-30 17:26:12,273:WARNING:c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\discriminant_analysis.py:926: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2023-05-30 17:26:12,283:WARNING:c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\discriminant_analysis.py:926: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2023-05-30 17:26:12,876:WARNING:c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-05-30 17:26:14,127:WARNING:c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\discriminant_analysis.py:926: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2023-05-30 17:26:14,174:WARNING:c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\discriminant_analysis.py:926: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2023-05-30 17:26:14,420:WARNING:c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-05-30 17:26:16,940:INFO:Calculating mean and std
2023-05-30 17:26:16,942:INFO:Creating metrics dataframe
2023-05-30 17:26:17,555:INFO:Uploading results into container
2023-05-30 17:26:17,556:INFO:Uploading model into container now
2023-05-30 17:26:17,558:INFO:_master_model_container: 8
2023-05-30 17:26:17,558:INFO:_display_container: 2
2023-05-30 17:26:17,558:INFO:QuadraticDiscriminantAnalysis(priors=None, reg_param=0.0,
                              store_covariance=False, tol=0.0001)
2023-05-30 17:26:17,560:INFO:create_model() successfully completed......................................
2023-05-30 17:26:17,716:INFO:SubProcess create_model() end ==================================
2023-05-30 17:26:17,718:INFO:Creating metrics dataframe
2023-05-30 17:26:17,750:INFO:Initializing Ada Boost Classifier
2023-05-30 17:26:17,750:INFO:Total runtime is 0.8320606748263041 minutes
2023-05-30 17:26:17,757:INFO:SubProcess create_model() called ==================================
2023-05-30 17:26:17,758:INFO:Initializing create_model()
2023-05-30 17:26:17,759:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000023F2193E890>, estimator=ada, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000023F1F325E70>, model_only=True, return_train_score=False, kwargs={})
2023-05-30 17:26:17,759:INFO:Checking exceptions
2023-05-30 17:26:17,760:INFO:Importing libraries
2023-05-30 17:26:17,760:INFO:Copying training dataset
2023-05-30 17:26:17,769:INFO:Defining folds
2023-05-30 17:26:17,769:INFO:Declaring metric variables
2023-05-30 17:26:17,777:INFO:Importing untrained model
2023-05-30 17:26:17,784:INFO:Ada Boost Classifier Imported successfully
2023-05-30 17:26:17,796:INFO:Starting cross validation
2023-05-30 17:26:17,801:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-05-30 17:26:23,406:INFO:Calculating mean and std
2023-05-30 17:26:23,408:INFO:Creating metrics dataframe
2023-05-30 17:26:24,195:INFO:Uploading results into container
2023-05-30 17:26:24,197:INFO:Uploading model into container now
2023-05-30 17:26:24,198:INFO:_master_model_container: 9
2023-05-30 17:26:24,198:INFO:_display_container: 2
2023-05-30 17:26:24,200:INFO:AdaBoostClassifier(algorithm='SAMME.R', base_estimator='deprecated',
                   estimator=None, learning_rate=1.0, n_estimators=50,
                   random_state=5668)
2023-05-30 17:26:24,200:INFO:create_model() successfully completed......................................
2023-05-30 17:26:24,365:INFO:SubProcess create_model() end ==================================
2023-05-30 17:26:24,366:INFO:Creating metrics dataframe
2023-05-30 17:26:24,392:INFO:Initializing Gradient Boosting Classifier
2023-05-30 17:26:24,393:INFO:Total runtime is 0.9427793900171916 minutes
2023-05-30 17:26:24,401:INFO:SubProcess create_model() called ==================================
2023-05-30 17:26:24,402:INFO:Initializing create_model()
2023-05-30 17:26:24,404:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000023F2193E890>, estimator=gbc, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000023F1F325E70>, model_only=True, return_train_score=False, kwargs={})
2023-05-30 17:26:24,404:INFO:Checking exceptions
2023-05-30 17:26:24,405:INFO:Importing libraries
2023-05-30 17:26:24,406:INFO:Copying training dataset
2023-05-30 17:26:24,415:INFO:Defining folds
2023-05-30 17:26:24,416:INFO:Declaring metric variables
2023-05-30 17:26:24,423:INFO:Importing untrained model
2023-05-30 17:26:24,432:INFO:Gradient Boosting Classifier Imported successfully
2023-05-30 17:26:24,446:INFO:Starting cross validation
2023-05-30 17:26:24,450:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-05-30 17:26:30,005:INFO:Calculating mean and std
2023-05-30 17:26:30,007:INFO:Creating metrics dataframe
2023-05-30 17:26:30,678:INFO:Uploading results into container
2023-05-30 17:26:30,681:INFO:Uploading model into container now
2023-05-30 17:26:30,683:INFO:_master_model_container: 10
2023-05-30 17:26:30,684:INFO:_display_container: 2
2023-05-30 17:26:30,685:INFO:GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='log_loss', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_samples_leaf=1,
                           min_samples_split=2, min_weight_fraction_leaf=0.0,
                           n_estimators=100, n_iter_no_change=None,
                           random_state=5668, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)
2023-05-30 17:26:30,686:INFO:create_model() successfully completed......................................
2023-05-30 17:26:30,855:INFO:SubProcess create_model() end ==================================
2023-05-30 17:26:30,856:INFO:Creating metrics dataframe
2023-05-30 17:26:30,887:INFO:Initializing Linear Discriminant Analysis
2023-05-30 17:26:30,888:INFO:Total runtime is 1.051026701927185 minutes
2023-05-30 17:26:30,897:INFO:SubProcess create_model() called ==================================
2023-05-30 17:26:30,898:INFO:Initializing create_model()
2023-05-30 17:26:30,900:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000023F2193E890>, estimator=lda, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000023F1F325E70>, model_only=True, return_train_score=False, kwargs={})
2023-05-30 17:26:30,901:INFO:Checking exceptions
2023-05-30 17:26:30,902:INFO:Importing libraries
2023-05-30 17:26:30,903:INFO:Copying training dataset
2023-05-30 17:26:30,910:INFO:Defining folds
2023-05-30 17:26:30,912:INFO:Declaring metric variables
2023-05-30 17:26:30,922:INFO:Importing untrained model
2023-05-30 17:26:30,928:INFO:Linear Discriminant Analysis Imported successfully
2023-05-30 17:26:30,943:INFO:Starting cross validation
2023-05-30 17:26:30,947:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-05-30 17:26:36,519:INFO:Calculating mean and std
2023-05-30 17:26:36,522:INFO:Creating metrics dataframe
2023-05-30 17:26:37,334:INFO:Uploading results into container
2023-05-30 17:26:37,338:INFO:Uploading model into container now
2023-05-30 17:26:37,339:INFO:_master_model_container: 11
2023-05-30 17:26:37,339:INFO:_display_container: 2
2023-05-30 17:26:37,339:INFO:LinearDiscriminantAnalysis(covariance_estimator=None, n_components=None,
                           priors=None, shrinkage=None, solver='svd',
                           store_covariance=False, tol=0.0001)
2023-05-30 17:26:37,339:INFO:create_model() successfully completed......................................
2023-05-30 17:26:37,534:INFO:SubProcess create_model() end ==================================
2023-05-30 17:26:37,535:INFO:Creating metrics dataframe
2023-05-30 17:26:37,568:INFO:Initializing Extra Trees Classifier
2023-05-30 17:26:37,568:INFO:Total runtime is 1.162364411354065 minutes
2023-05-30 17:26:37,576:INFO:SubProcess create_model() called ==================================
2023-05-30 17:26:37,577:INFO:Initializing create_model()
2023-05-30 17:26:37,578:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000023F2193E890>, estimator=et, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000023F1F325E70>, model_only=True, return_train_score=False, kwargs={})
2023-05-30 17:26:37,578:INFO:Checking exceptions
2023-05-30 17:26:37,580:INFO:Importing libraries
2023-05-30 17:26:37,580:INFO:Copying training dataset
2023-05-30 17:26:37,590:INFO:Defining folds
2023-05-30 17:26:37,591:INFO:Declaring metric variables
2023-05-30 17:26:37,599:INFO:Importing untrained model
2023-05-30 17:26:37,599:INFO:Extra Trees Classifier Imported successfully
2023-05-30 17:26:37,625:INFO:Starting cross validation
2023-05-30 17:26:37,629:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-05-30 17:26:45,321:INFO:Calculating mean and std
2023-05-30 17:26:45,322:INFO:Creating metrics dataframe
2023-05-30 17:26:45,794:INFO:Uploading results into container
2023-05-30 17:26:45,796:INFO:Uploading model into container now
2023-05-30 17:26:45,797:INFO:_master_model_container: 12
2023-05-30 17:26:45,798:INFO:_display_container: 2
2023-05-30 17:26:45,799:INFO:ExtraTreesClassifier(bootstrap=False, ccp_alpha=0.0, class_weight=None,
                     criterion='gini', max_depth=None, max_features='sqrt',
                     max_leaf_nodes=None, max_samples=None,
                     min_impurity_decrease=0.0, min_samples_leaf=1,
                     min_samples_split=2, min_weight_fraction_leaf=0.0,
                     n_estimators=100, n_jobs=-1, oob_score=False,
                     random_state=5668, verbose=0, warm_start=False)
2023-05-30 17:26:45,799:INFO:create_model() successfully completed......................................
2023-05-30 17:26:45,930:INFO:SubProcess create_model() end ==================================
2023-05-30 17:26:45,931:INFO:Creating metrics dataframe
2023-05-30 17:26:45,954:INFO:Initializing Extreme Gradient Boosting
2023-05-30 17:26:45,955:INFO:Total runtime is 1.3021422942479453 minutes
2023-05-30 17:26:45,961:INFO:SubProcess create_model() called ==================================
2023-05-30 17:26:45,961:INFO:Initializing create_model()
2023-05-30 17:26:45,962:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000023F2193E890>, estimator=xgboost, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000023F1F325E70>, model_only=True, return_train_score=False, kwargs={})
2023-05-30 17:26:45,962:INFO:Checking exceptions
2023-05-30 17:26:45,963:INFO:Importing libraries
2023-05-30 17:26:45,963:INFO:Copying training dataset
2023-05-30 17:26:45,969:INFO:Defining folds
2023-05-30 17:26:45,970:INFO:Declaring metric variables
2023-05-30 17:26:45,975:INFO:Importing untrained model
2023-05-30 17:26:45,980:INFO:Extreme Gradient Boosting Imported successfully
2023-05-30 17:26:45,990:INFO:Starting cross validation
2023-05-30 17:26:45,992:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-05-30 17:26:51,837:INFO:Calculating mean and std
2023-05-30 17:26:51,838:INFO:Creating metrics dataframe
2023-05-30 17:26:52,616:INFO:Uploading results into container
2023-05-30 17:26:52,618:INFO:Uploading model into container now
2023-05-30 17:26:52,620:INFO:_master_model_container: 13
2023-05-30 17:26:52,621:INFO:_display_container: 2
2023-05-30 17:26:52,623:INFO:XGBClassifier(base_score=None, booster='gbtree', callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              n_estimators=100, n_jobs=-1, num_parallel_tree=None,
              objective='binary:logistic', predictor=None, ...)
2023-05-30 17:26:52,623:INFO:create_model() successfully completed......................................
2023-05-30 17:26:52,796:INFO:SubProcess create_model() end ==================================
2023-05-30 17:26:52,796:INFO:Creating metrics dataframe
2023-05-30 17:26:52,821:INFO:Initializing Light Gradient Boosting Machine
2023-05-30 17:26:52,821:INFO:Total runtime is 1.4165744344393414 minutes
2023-05-30 17:26:52,826:INFO:SubProcess create_model() called ==================================
2023-05-30 17:26:52,828:INFO:Initializing create_model()
2023-05-30 17:26:52,828:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000023F2193E890>, estimator=lightgbm, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000023F1F325E70>, model_only=True, return_train_score=False, kwargs={})
2023-05-30 17:26:52,829:INFO:Checking exceptions
2023-05-30 17:26:52,829:INFO:Importing libraries
2023-05-30 17:26:52,829:INFO:Copying training dataset
2023-05-30 17:26:52,841:INFO:Defining folds
2023-05-30 17:26:52,842:INFO:Declaring metric variables
2023-05-30 17:26:52,853:INFO:Importing untrained model
2023-05-30 17:26:52,859:INFO:Light Gradient Boosting Machine Imported successfully
2023-05-30 17:26:52,876:INFO:Starting cross validation
2023-05-30 17:26:52,879:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-05-30 17:27:00,271:INFO:Calculating mean and std
2023-05-30 17:27:00,272:INFO:Creating metrics dataframe
2023-05-30 17:27:00,753:INFO:Uploading results into container
2023-05-30 17:27:00,755:INFO:Uploading model into container now
2023-05-30 17:27:00,756:INFO:_master_model_container: 14
2023-05-30 17:27:00,756:INFO:_display_container: 2
2023-05-30 17:27:00,757:INFO:LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
               importance_type='split', learning_rate=0.1, max_depth=-1,
               min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
               n_estimators=100, n_jobs=-1, num_leaves=31, objective=None,
               random_state=5668, reg_alpha=0.0, reg_lambda=0.0, silent='warn',
               subsample=1.0, subsample_for_bin=200000, subsample_freq=0)
2023-05-30 17:27:00,757:INFO:create_model() successfully completed......................................
2023-05-30 17:27:00,904:INFO:SubProcess create_model() end ==================================
2023-05-30 17:27:00,905:INFO:Creating metrics dataframe
2023-05-30 17:27:00,929:INFO:Initializing CatBoost Classifier
2023-05-30 17:27:00,929:INFO:Total runtime is 1.551716991265615 minutes
2023-05-30 17:27:00,935:INFO:SubProcess create_model() called ==================================
2023-05-30 17:27:00,937:INFO:Initializing create_model()
2023-05-30 17:27:00,937:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000023F2193E890>, estimator=catboost, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000023F1F325E70>, model_only=True, return_train_score=False, kwargs={})
2023-05-30 17:27:00,938:INFO:Checking exceptions
2023-05-30 17:27:00,938:INFO:Importing libraries
2023-05-30 17:27:00,939:INFO:Copying training dataset
2023-05-30 17:27:00,944:INFO:Defining folds
2023-05-30 17:27:00,945:INFO:Declaring metric variables
2023-05-30 17:27:00,950:INFO:Importing untrained model
2023-05-30 17:27:00,955:INFO:CatBoost Classifier Imported successfully
2023-05-30 17:27:00,964:INFO:Starting cross validation
2023-05-30 17:27:00,966:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-05-30 17:27:20,154:WARNING:c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\model_selection\_validation.py:378: FitFailedWarning: 
3 fits failed out of a total of 10.
The score on these train-test partitions for these parameters will be set to 0.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
1 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\pycaret\internal\pipeline.py", line 260, in fit
    fitted_estimator = self._memory_fit(
  File "c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\joblib\memory.py", line 594, in __call__
    return self._cached_call(args, kwargs)[0]
  File "c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\pycaret\internal\memory.py", line 398, in _cached_call
    out, metadata = self.call(*args, **kwargs)
  File "c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\pycaret\internal\memory.py", line 309, in call
    output = self.func(*args, **kwargs)
  File "c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\pycaret\internal\pipeline.py", line 66, in _fit_one
    transformer.fit(*args, **fit_params)
  File "c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\catboost\core.py", line 5131, in fit
    self._fit(X, y, cat_features, text_features, embedding_features, None, sample_weight, None, None, None, None, baseline, use_best_model,
  File "c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\catboost\core.py", line 2357, in _fit
    self._train(
  File "c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\catboost\core.py", line 1761, in _train
    self._object._train(train_pool, test_pool, params, allow_clear_pool, init_model._object if init_model else None)
  File "_catboost.pyx", line 4624, in _catboost._CatBoost._train
  File "_catboost.pyx", line 4673, in _catboost._CatBoost._train
_catboost.CatBoostError

--------------------------------------------------------------------------------
1 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\pycaret\internal\pipeline.py", line 260, in fit
    fitted_estimator = self._memory_fit(
  File "c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\joblib\memory.py", line 594, in __call__
    return self._cached_call(args, kwargs)[0]
  File "c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\pycaret\internal\memory.py", line 398, in _cached_call
    out, metadata = self.call(*args, **kwargs)
  File "c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\pycaret\internal\memory.py", line 309, in call
    output = self.func(*args, **kwargs)
  File "c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\pycaret\internal\pipeline.py", line 66, in _fit_one
    transformer.fit(*args, **fit_params)
  File "c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\catboost\core.py", line 5131, in fit
    self._fit(X, y, cat_features, text_features, embedding_features, None, sample_weight, None, None, None, None, baseline, use_best_model,
  File "c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\catboost\core.py", line 2357, in _fit
    self._train(
  File "c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\catboost\core.py", line 1761, in _train
    self._object._train(train_pool, test_pool, params, allow_clear_pool, init_model._object if init_model else None)
  File "_catboost.pyx", line 4624, in _catboost._CatBoost._train
  File "_catboost.pyx", line 4673, in _catboost._CatBoost._train
_catboost.CatBoostError: C:/Go_Agent/pipelines/BuildMaster/catboost.git/catboost/libs/train_lib/dir_helper.cpp:26: Can't create train tmp dir: tmp

--------------------------------------------------------------------------------
1 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\pycaret\internal\pipeline.py", line 260, in fit
    fitted_estimator = self._memory_fit(
  File "c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\joblib\memory.py", line 594, in __call__
    return self._cached_call(args, kwargs)[0]
  File "c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\pycaret\internal\memory.py", line 398, in _cached_call
    out, metadata = self.call(*args, **kwargs)
  File "c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\pycaret\internal\memory.py", line 309, in call
    output = self.func(*args, **kwargs)
  File "c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\pycaret\internal\pipeline.py", line 66, in _fit_one
    transformer.fit(*args, **fit_params)
  File "c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\catboost\core.py", line 5131, in fit
    self._fit(X, y, cat_features, text_features, embedding_features, None, sample_weight, None, None, None, None, baseline, use_best_model,
  File "c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\catboost\core.py", line 2357, in _fit
    self._train(
  File "c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\catboost\core.py", line 1761, in _train
    self._object._train(train_pool, test_pool, params, allow_clear_pool, init_model._object if init_model else None)
  File "_catboost.pyx", line 4624, in _catboost._CatBoost._train
  File "_catboost.pyx", line 4673, in _catboost._CatBoost._train
_catboost.CatBoostError: C:/Go_Agent/pipelines/BuildMaster/catboost.git/catboost/libs/train_lib/dir_helper.cpp:20: Can't create train working dir: catboost_info

  warnings.warn(some_fits_failed_message, FitFailedWarning)

2023-05-30 17:27:20,154:INFO:Calculating mean and std
2023-05-30 17:27:20,156:INFO:Creating metrics dataframe
2023-05-30 17:27:20,797:INFO:Uploading results into container
2023-05-30 17:27:20,798:INFO:Uploading model into container now
2023-05-30 17:27:20,800:INFO:_master_model_container: 15
2023-05-30 17:27:20,801:INFO:_display_container: 2
2023-05-30 17:27:20,801:INFO:<catboost.core.CatBoostClassifier object at 0x0000023F228EAA10>
2023-05-30 17:27:20,802:INFO:create_model() successfully completed......................................
2023-05-30 17:27:20,961:WARNING:create_model() for <catboost.core.CatBoostClassifier object at 0x0000023F228EAA10> raised an exception or returned all 0.0, trying without fit_kwargs:
2023-05-30 17:27:20,964:WARNING:Traceback (most recent call last):
  File "c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\pycaret\internal\pycaret_experiment\supervised_experiment.py", line 795, in compare_models
    np.sum(
AssertionError

2023-05-30 17:27:20,965:INFO:Initializing create_model()
2023-05-30 17:27:20,966:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000023F2193E890>, estimator=catboost, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000023F1F325E70>, model_only=True, return_train_score=False, kwargs={})
2023-05-30 17:27:20,967:INFO:Checking exceptions
2023-05-30 17:27:20,967:INFO:Importing libraries
2023-05-30 17:27:20,968:INFO:Copying training dataset
2023-05-30 17:27:20,977:INFO:Defining folds
2023-05-30 17:27:20,978:INFO:Declaring metric variables
2023-05-30 17:27:20,987:INFO:Importing untrained model
2023-05-30 17:27:20,994:INFO:CatBoost Classifier Imported successfully
2023-05-30 17:27:21,007:INFO:Starting cross validation
2023-05-30 17:27:21,010:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-05-30 17:27:33,228:INFO:Calculating mean and std
2023-05-30 17:27:33,232:INFO:Creating metrics dataframe
2023-05-30 17:27:34,409:INFO:Uploading results into container
2023-05-30 17:27:34,412:INFO:Uploading model into container now
2023-05-30 17:27:34,416:INFO:_master_model_container: 16
2023-05-30 17:27:34,418:INFO:_display_container: 2
2023-05-30 17:27:34,420:INFO:<catboost.core.CatBoostClassifier object at 0x0000023F229AF8B0>
2023-05-30 17:27:34,422:INFO:create_model() successfully completed......................................
2023-05-30 17:27:34,674:INFO:SubProcess create_model() end ==================================
2023-05-30 17:27:34,676:INFO:Creating metrics dataframe
2023-05-30 17:27:34,719:INFO:Initializing Dummy Classifier
2023-05-30 17:27:34,721:INFO:Total runtime is 2.114923417568207 minutes
2023-05-30 17:27:34,731:INFO:SubProcess create_model() called ==================================
2023-05-30 17:27:34,732:INFO:Initializing create_model()
2023-05-30 17:27:34,732:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000023F2193E890>, estimator=dummy, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x0000023F1F325E70>, model_only=True, return_train_score=False, kwargs={})
2023-05-30 17:27:34,738:INFO:Checking exceptions
2023-05-30 17:27:34,740:INFO:Importing libraries
2023-05-30 17:27:34,741:INFO:Copying training dataset
2023-05-30 17:27:34,755:INFO:Defining folds
2023-05-30 17:27:34,763:INFO:Declaring metric variables
2023-05-30 17:27:34,775:INFO:Importing untrained model
2023-05-30 17:27:34,786:INFO:Dummy Classifier Imported successfully
2023-05-30 17:27:34,808:INFO:Starting cross validation
2023-05-30 17:27:34,812:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2023-05-30 17:27:42,932:INFO:Calculating mean and std
2023-05-30 17:27:42,943:INFO:Creating metrics dataframe
2023-05-30 17:27:43,672:INFO:Uploading results into container
2023-05-30 17:27:43,675:INFO:Uploading model into container now
2023-05-30 17:27:43,676:INFO:_master_model_container: 17
2023-05-30 17:27:43,677:INFO:_display_container: 2
2023-05-30 17:27:43,678:INFO:DummyClassifier(constant=None, random_state=5668, strategy='prior')
2023-05-30 17:27:43,678:INFO:create_model() successfully completed......................................
2023-05-30 17:27:43,864:INFO:SubProcess create_model() end ==================================
2023-05-30 17:27:43,865:INFO:Creating metrics dataframe
2023-05-30 17:27:43,909:INFO:Initializing create_model()
2023-05-30 17:27:43,910:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000023F2193E890>, estimator=RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='sqrt',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       n_estimators=100, n_jobs=-1, oob_score=False,
                       random_state=5668, verbose=0, warm_start=False), fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=False, predict=False, fit_kwargs={}, groups=None, refit=True, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=None, model_only=True, return_train_score=False, kwargs={})
2023-05-30 17:27:43,911:INFO:Checking exceptions
2023-05-30 17:27:43,914:INFO:Importing libraries
2023-05-30 17:27:43,915:INFO:Copying training dataset
2023-05-30 17:27:43,924:INFO:Defining folds
2023-05-30 17:27:43,925:INFO:Declaring metric variables
2023-05-30 17:27:43,926:INFO:Importing untrained model
2023-05-30 17:27:43,926:INFO:Declaring custom model
2023-05-30 17:27:43,928:INFO:Random Forest Classifier Imported successfully
2023-05-30 17:27:43,930:INFO:Cross validation set to False
2023-05-30 17:27:43,931:INFO:Fitting Model
2023-05-30 17:27:45,243:INFO:RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='sqrt',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       n_estimators=100, n_jobs=-1, oob_score=False,
                       random_state=5668, verbose=0, warm_start=False)
2023-05-30 17:27:45,243:INFO:create_model() successfully completed......................................
2023-05-30 17:27:45,492:INFO:_master_model_container: 17
2023-05-30 17:27:45,494:INFO:_display_container: 2
2023-05-30 17:27:45,495:INFO:RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='sqrt',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       n_estimators=100, n_jobs=-1, oob_score=False,
                       random_state=5668, verbose=0, warm_start=False)
2023-05-30 17:27:45,496:INFO:compare_models() successfully completed......................................
2023-05-30 17:28:40,253:INFO:Initializing predict_model()
2023-05-30 17:28:40,254:INFO:predict_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x0000023F2193E890>, estimator=RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='sqrt',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       n_estimators=100, n_jobs=-1, oob_score=False,
                       random_state=5668, verbose=0, warm_start=False), probability_threshold=None, encoded_labels=False, raw_score=False, round=4, verbose=True, ml_usecase=None, preprocess=True, encode_labels=<function _SupervisedExperiment.predict_model.<locals>.encode_labels at 0x0000023F22905A20>)
2023-05-30 17:28:40,255:INFO:Checking exceptions
2023-05-30 17:28:40,255:INFO:Preloading libraries
2023-05-30 17:28:40,263:INFO:Set up data.
2023-05-30 17:28:40,278:INFO:Set up index.
2023-05-30 17:28:40,669:WARNING:c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\pycaret\utils\generic.py:586: UserWarning: Traceback (most recent call last):
  File "c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\pycaret\utils\generic.py", line 580, in _calculate_metric
    calculated_metric = score_func(y_test, target, sample_weight=weights, **kwargs)
  File "c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\pycaret\internal\metrics.py", line 35, in __call__
    return self.score_func(y_true, y_pred, **kwargs)
  File "c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_ranking.py", line 572, in roc_auc_score
    return _average_binary_score(
  File "c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_base.py", line 75, in _average_binary_score
    return binary_metric(y_true, y_score, sample_weight=sample_weight)
  File "c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_ranking.py", line 339, in _binary_roc_auc_score
    raise ValueError(
ValueError: Only one class present in y_true. ROC AUC score is not defined in that case.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\pycaret\utils\generic.py", line 584, in _calculate_metric
    calculated_metric = score_func(y_test, target, **kwargs)
  File "c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\pycaret\internal\metrics.py", line 35, in __call__
    return self.score_func(y_true, y_pred, **kwargs)
  File "c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_ranking.py", line 572, in roc_auc_score
    return _average_binary_score(
  File "c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_base.py", line 75, in _average_binary_score
    return binary_metric(y_true, y_score, sample_weight=sample_weight)
  File "c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_ranking.py", line 339, in _binary_roc_auc_score
    raise ValueError(
ValueError: Only one class present in y_true. ROC AUC score is not defined in that case.

  warnings.warn(traceback.format_exc())

2023-05-30 17:28:40,672:WARNING:c:\Users\Jef\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 due to no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

2023-05-30 17:28:52,984:INFO:Initializing save_model()
2023-05-30 17:28:52,984:INFO:save_model(model=RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='sqrt',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       n_estimators=100, n_jobs=-1, oob_score=False,
                       random_state=5668, verbose=0, warm_start=False), model_name=ridge-model, prep_pipe_=Pipeline(memory=FastMemory(location=C:\Users\Jef\AppData\Local\Temp\joblib),
         steps=[('numerical_imputer',
                 TransformerWrapper(exclude=None,
                                    include=['age', 'trestbps', 'chol',
                                             'oldpeak', 'slope', 'ca', 'thal'],
                                    transformer=SimpleImputer(add_indicator=False,
                                                              copy=True,
                                                              fill_value=None,
                                                              keep_empty_features=False,
                                                              missing_values=nan,
                                                              strategy='mean',
                                                              verbose='deprecat...
                                                              handle_missing='return_nan',
                                                              handle_unknown='value',
                                                              return_df=True,
                                                              use_cat_names=True,
                                                              verbose=0))),
                ('rest_encoding',
                 TransformerWrapper(exclude=None, include=['thalach'],
                                    transformer=TargetEncoder(cols=[],
                                                              drop_invariant=False,
                                                              handle_missing='return_nan',
                                                              handle_unknown='value',
                                                              hierarchy=None,
                                                              min_samples_leaf=20,
                                                              return_df=True,
                                                              smoothing=10,
                                                              verbose=0)))],
         verbose=False), verbose=True, use_case=MLUsecase.CLASSIFICATION, kwargs={})
2023-05-30 17:28:52,984:INFO:Adding model into prep_pipe
2023-05-30 17:28:53,066:INFO:ridge-model.pkl saved in current working directory
2023-05-30 17:28:53,134:INFO:Pipeline(memory=FastMemory(location=C:\Users\Jef\AppData\Local\Temp\joblib),
         steps=[('numerical_imputer',
                 TransformerWrapper(exclude=None,
                                    include=['age', 'trestbps', 'chol',
                                             'oldpeak', 'slope', 'ca', 'thal'],
                                    transformer=SimpleImputer(add_indicator=False,
                                                              copy=True,
                                                              fill_value=None,
                                                              keep_empty_features=False,
                                                              missing_values=nan,
                                                              strategy='mean',
                                                              verbose='deprecat...
                 RandomForestClassifier(bootstrap=True, ccp_alpha=0.0,
                                        class_weight=None, criterion='gini',
                                        max_depth=None, max_features='sqrt',
                                        max_leaf_nodes=None, max_samples=None,
                                        min_impurity_decrease=0.0,
                                        min_samples_leaf=1, min_samples_split=2,
                                        min_weight_fraction_leaf=0.0,
                                        n_estimators=100, n_jobs=-1,
                                        oob_score=False, random_state=5668,
                                        verbose=0, warm_start=False))],
         verbose=False)
2023-05-30 17:28:53,134:INFO:save_model() successfully completed......................................
2023-05-30 17:28:56,388:INFO:Initializing load_model()
2023-05-30 17:28:56,388:INFO:load_model(model_name=ridge-model, platform=None, authentication=None, verbose=True)
